# Generated by Django 6.0.6 on 2026-07-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tk', 'تکنولوژی'), ('pro', 'برنامه نویس'), ('hosh', 'هوش مصنوعی'), ('blak', 'بلاکچین')], default='سایر', max_length=20),
        ),
    ]
